# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oilmarket.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foilmarket.proto\x12\toilmarket\"/\n\x0bSignRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\"!\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\"c\n\x0bSellRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\r\n\x05\x62uyer\x18\x02 \x01(\t\x12\x10\n\x08\x61ttester\x18\x03 \x01(\t\x12\x0f\n\x07request\x18\x04 \x01(\x0c\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"\x1c\n\x0cSellResponse\x12\x0c\n\x04\x66lag\x18\x01 \x01(\t\"C\n\x12\x43reateBuyerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66lag\x18\x02 \x01(\t\x12\x11\n\tattesters\x18\x03 \x03(\t\"%\n\x15\x43reateAttesterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x13\x43reateSellerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0e\x41piKeyResponse\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"#\n\x10\x41\x64\x64\x42\x61rrelRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"\x1f\n\x11\x41\x64\x64\x42\x61rrelResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xa8\x03\n\tOilmarket\x12\x37\n\x04Sign\x12\x16.oilmarket.SignRequest\x1a\x17.oilmarket.SignResponse\x12\x37\n\x04Sell\x12\x16.oilmarket.SellRequest\x1a\x17.oilmarket.SellResponse\x12G\n\x0b\x43reateBuyer\x12\x1d.oilmarket.CreateBuyerRequest\x1a\x19.oilmarket.ApiKeyResponse\x12M\n\x0e\x43reateAttester\x12 .oilmarket.CreateAttesterRequest\x1a\x19.oilmarket.ApiKeyResponse\x12I\n\x0c\x43reateSeller\x12\x1e.oilmarket.CreateSellerRequest\x1a\x19.oilmarket.ApiKeyResponse\x12\x46\n\tAddBarrel\x12\x1b.oilmarket.AddBarrelRequest\x1a\x1c.oilmarket.AddBarrelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oilmarket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIGNREQUEST']._serialized_start=30
  _globals['_SIGNREQUEST']._serialized_end=77
  _globals['_SIGNRESPONSE']._serialized_start=79
  _globals['_SIGNRESPONSE']._serialized_end=112
  _globals['_SELLREQUEST']._serialized_start=114
  _globals['_SELLREQUEST']._serialized_end=213
  _globals['_SELLRESPONSE']._serialized_start=215
  _globals['_SELLRESPONSE']._serialized_end=243
  _globals['_CREATEBUYERREQUEST']._serialized_start=245
  _globals['_CREATEBUYERREQUEST']._serialized_end=312
  _globals['_CREATEATTESTERREQUEST']._serialized_start=314
  _globals['_CREATEATTESTERREQUEST']._serialized_end=351
  _globals['_CREATESELLERREQUEST']._serialized_start=353
  _globals['_CREATESELLERREQUEST']._serialized_end=388
  _globals['_APIKEYRESPONSE']._serialized_start=390
  _globals['_APIKEYRESPONSE']._serialized_end=423
  _globals['_ADDBARRELREQUEST']._serialized_start=425
  _globals['_ADDBARRELREQUEST']._serialized_end=460
  _globals['_ADDBARRELRESPONSE']._serialized_start=462
  _globals['_ADDBARRELRESPONSE']._serialized_end=493
  _globals['_OILMARKET']._serialized_start=496
  _globals['_OILMARKET']._serialized_end=920
# @@protoc_insertion_point(module_scope)
