# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluwal/bluwal_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.bluwal import bluwal_pb2 as bluwal_dot_bluwal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62luwal/bluwal_service.proto\x12\x06\x62luwal\x1a\x13\x62luwal/bluwal.proto2\x96\x04\n\rBluwalService\x12L\n\rContestCreate\x12\x1c.bluwal.ContestCreateRequest\x1a\x1d.bluwal.ContestCreateResponse\x12\x43\n\nContestGet\x12\x19.bluwal.ContestGetRequest\x1a\x1a.bluwal.ContestGetResponse\x12\x46\n\x0b\x43ontestList\x12\x1a.bluwal.ContestListRequest\x1a\x1b.bluwal.ContestListResponse\x12L\n\rContestEnroll\x12\x1c.bluwal.ContestEnrollRequest\x1a\x1d.bluwal.ContestEnrollResponse\x12R\n\x0f\x43hallengeSubmit\x12\x1e.bluwal.ChallengeSubmitRequest\x1a\x1f.bluwal.ChallengeSubmitResponse\x12@\n\tCheckGoal\x12\x18.bluwal.CheckGoalRequest\x1a\x19.bluwal.CheckGoalResponse\x12\x46\n\x0b\x43laimReward\x12\x1a.bluwal.ClaimRewardRequest\x1a\x1b.bluwal.ClaimRewardResponseBq\n\ncom.bluwalB\x12\x42luwalServiceProtoP\x01Z\x17\x62luwal/pkg/proto/bluwal\xa2\x02\x03\x42XX\xaa\x02\x06\x42luwal\xca\x02\x06\x42luwal\xe2\x02\x12\x42luwal\\GPBMetadata\xea\x02\x06\x42luwalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bluwal.bluwal_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.bluwalB\022BluwalServiceProtoP\001Z\027bluwal/pkg/proto/bluwal\242\002\003BXX\252\002\006Bluwal\312\002\006Bluwal\342\002\022Bluwal\\GPBMetadata\352\002\006Bluwal'
  _globals['_BLUWALSERVICE']._serialized_start=61
  _globals['_BLUWALSERVICE']._serialized_end=595
# @@protoc_insertion_point(module_scope)
